baseURL = 'https://www.cyberclublsu.com'
languageCode = 'en-us'
title = 'Security Society at LSU'
theme = 'hugo386'

[params]
    mainpagetitle = 'Security Society at LSU'
    mainpagesubtitle = 'Hackers Welcome'
    mainpagedesc = 'SSL is the foremost resource for learning cybersecurity through doing at LSU.'

    showhugo = false

    github = 'https://github.com/Hyper-Tiger-Transfer-Protocol'
    loadfastload = true

[menu]
    [[menu.main]]
        identifier = 'about'
        name = 'About'
        url = '/about/'
        weight = 10
    [[menu.main]]
        identifier = 'ctf'
        name = 'Challenges'
        url = '/ctf/'
        weight = 20

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
